### ISSUE TITLE
StructuralTestProvider: outer class is mistakenly used as the package name of a misplaced class

### ISSUE THREAD

**Issue by martinmo** [ls1intum/Ares#294] opened 2023-05-17 14:26 UTC
**Describe the bug**
The error message for a misplaced class is wrong if the class is put in an inner class instead of a package. The outer class name will be used as the package name.

Example error message:

"The class SomeClass has the correct name, but the package it's in, [OuterClass], deviates from the expectation.  Make sure it is placed in the correct package."

**To Reproduce**

Use this `test.json` snippet together with a `StructuralTestProvider` such as `MethodTestProvider`:

```json
[{
    "class": {
      "name": "SomeClass",
      "package": ""
    }
}]
```

Student submits the following code:

```java
class OuterClass {
    class SomeClass {
    }
}
```

**Expected behavior**
I suggest the error message should say: "The class SomeClass has the correct name, but it should not be an inner class of OuterClass.  Make sure it is placed in the correct location."

**Additional context**
Ares version: 1.11.3

**Comment by MaisiKoleni** [comment] 2023-06-22 20:24
I guess this is because it has no package name, so `OuterClass.SomeClass` becomes `OuterClass` package, `SomeClass` class name.

For now, I would fix this such that the package name is correctly split. This will end up as
`The exercise expects a class with the name SomeClass in the package <default> (i.e., no package). You did not implement the class in the exercise.`

Finding nested classes correctly and providing specialized failure messages is more work than I have time available for Ares.
Feel free to open a PR for that, though, if this is not satisfactory. We may eventually have a go at it ourselves, but that may take some time.

**Comment by MaisiKoleni** [comment] 2023-06-22 20:57
When I try to reproduce the bug, Ares already does what I proposed in the previous comment. The class name scanner does not look at the file content, so it is unable to find `SomeClass`. The package name is only constructed from the file path. For your example, I cannot reproduce the failure message given in this bug report. But it should be possible to get that message if a second class `SomeClass.java` is located in the folder/package `OuterClass`.
Could you please check again, if there is anything surrounding the two files you provided? There has to be more because Ares does not generate a class test for the given `test.json`.

**Comment by MaisiKoleni** [comment] 2023-06-22 21:11
Tried to reproduce again using the exact same version, test.json and class, I always get `org.opentest4j.AssertionFailedError: The exercise expects a class with the name SomeClass in the package . You did not implement the class in the exercise.`

Marked this issue as invalid until the information is corrected. If this issue turns out not to be a bug, don't hesitate to close it.

**Comment by MaisiKoleni** [comment] 2023-07-22 20:16
Closing this due to one month inactivity and not being reproducible without further information.
You are welcome to reopen it and provide new information/instructions based on my comments.
But right now, it doesn't seem like there's a problem that can be solved.

**Closed by MaisiKoleni** 2023-07-22 20:16 UTC
Labels: bug, invalid, question, structural-tests
